// Approved faculty email addresses (case-insensitive comparison enforced at lookup)
const FACULTY_EMAILS = new Set([
  'faculty01@university.edu',
  'faculty02@university.edu',
  'faculty03@university.edu',
  'faculty04@university.edu',
  'faculty05@university.edu',
  'faculty06@university.edu',
  'faculty07@university.edu',
  'faculty08@university.edu',
  'faculty09@university.edu',
  'faculty10@university.edu',
  'faculty11@university.edu',
  'faculty12@university.edu',
  'faculty13@university.edu',
  'faculty14@university.edu',
  'faculty15@university.edu',
  'faculty16@university.edu',
  'faculty17@university.edu',
  'faculty18@university.edu',
  'faculty19@university.edu',
  'faculty20@university.edu',
  'faculty21@university.edu',
  'faculty22@university.edu',
  'faculty23@university.edu',
  'faculty24@university.edu',
  'faculty25@university.edu',
  'faculty26@university.edu',
  'faculty27@university.edu',
  'faculty28@university.edu',
  'faculty29@university.edu',
  'faculty30@university.edu',
  'faculty31@university.edu',
  'faculty32@university.edu',
  'faculty33@university.edu',
  'faculty34@university.edu',
  'faculty35@university.edu',
  'faculty36@university.edu',
  'faculty37@university.edu',
  'faculty38@university.edu',
  'faculty39@university.edu',
  'faculty40@university.edu',
  'faculty41@university.edu',
  'faculty42@university.edu',
  'faculty43@university.edu',
  'faculty44@university.edu',
  'faculty45@university.edu',
]);

function isApprovedFaculty(email) {
  return FACULTY_EMAILS.has(email.trim().toLowerCase());
}

module.exports = { isApprovedFaculty };
